---
- name: My task
  hosts: all
  tasks:
     - name: Leaving a mark
       command: "touch /tmp/ansible_was_here"
     - name: Upgrade the OS
       become: yes 
       apt:
          update_cache: yes
          upgrade: yes
          autoremove: yes
